name: Send a telegram message to test everything works fine
on:
  reddit:
    url: https://www.reddit.com/r/nearprog/new/
    source: json
    config:
      limit: 1
      active: true
      force: true
      
jobs:
  telegram:
    name: Send a telegram message html
    runs-on: ubuntu-latest
    steps:    
      - name: Send a telegram photo message
        uses: appleboy/telegram-action@0.0.3
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_DUMMY_BOT_TOKEN }}
          message: thumb
          format: markdown
          photo: https://a.thumbs.redditmedia.com/RU60Z6_dLKVp5tO10NIk30hr6ScY0Lb8sqZJg_HF198.jpg 
          #${{ on.reddit.outputs.thumbnail }}


      - name: Send a telegram message html
        uses: appleboy/telegram-action@0.0.3
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_DUMMY_BOT_TOKEN }}
          message: |
            <a>${{ on.reddit.outputs.title }}</a>           
            <a href="https://song.link/${{ on.reddit.outputs.url }}">&#8205;</a> 
            <a href="https://www.reddit.com${{ on.reddit.outputs.permalink }}">🔗 Link to the post</a>
            
            <a href="https://song.link/${{ on.reddit.outputs.url }}">🎵 Listen on your favorite platform</a>
            
            <a href="https://www.epochconverter.com/?q=${{ on.reddit.outputs.created_utc }}&tz=Asia/Jerusalem">⏱️ Posted at</a>
          format: html
