name: Doing some tests (telegram only)
on:
  reddit:
    url: https://www.reddit.com/r/nearprog/new/
    source: json
    config:
      active: true
      force: true
      limit: 0
      filter:
        link_flair_text:
          $not:
            $regex: (Announcement|Contest|Discussion)
        sort:
          id: -1
        
jobs:
  telegram:
    name: Send a telegram message html
    runs-on: ubuntu-latest
    steps:    
      - name: Send a telegram message html
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO_ME }}
          token: ${{ secrets.TELEGRAM_DUMMY_BOT_TOKEN }}
          message: |
            <a>${{ on.reddit.outputs.title }}</a>           
            <a href="https://song.link/${{ on.reddit.outputs.url }}">&#8205;</a> 
            <a href="https://www.reddit.com${{ on.reddit.outputs.permalink }}">🔗 Link to the post</a>
            
            <a href="https://song.link/${{ on.reddit.outputs.url }}">🎵 Listen on your favorite platform</a>            
          format: html
