  
# telegram only

# pull one post from r/listentothis

name: Send a telegram message to test everything works fine
on:
  reddit:
    url: https://www.reddit.com/r/listentothis/new
    source: json
    config:
    
# change limit number to 1 to run

      limit: 1
jobs:
  telegram:
    name: Send a telegram message html
    runs-on: ubuntu-latest
    steps:    
      - name: Send a telegram message html
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            <a>${{ on.reddit.outputs.title }}</a>           
            <a href="https://song.link/${{ on.reddit.outputs.url }}">&#8205;</a> 
            <a href="https://www.reddit.com${{ on.reddit.outputs.permalink }}">🔗 Link to the post</a>
            
            <a href="https://song.link/${{ on.reddit.outputs.url }}">🎵 Listen on your favorite platform</a>

          format: html


 
